version: "3.9"
services:
  microservice:
    build:
      context: .
      args:
        - JAR_FILE=target/*.jar
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID="AKIAIOSFODNN7EXAMPLE"
      - AWS_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
